apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  selector:
    matchLabels:
      app: test2
  replicas: 1
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - name: test2
        image: nginx:latest
        ports:
        - containerPort: 80
